"""모델 학습과 추론에서 공유하는 기본 설정."""

RANDOM_STATE = 42
TARGET_COLUMN = "target_volume"
TIME_SPLIT_RATIO = 0.8
BASELINE_N_ESTIMATORS = 200
BASELINE_LEARNING_RATE = 0.05
BASELINE_SUBSAMPLE = 0.8
BASELINE_COLSAMPLE_BYTREE = 0.8
